print("Bienvenidos a python🐍")
print("######Cartel 6°B######")
print("######PROGRAMANDO######")
print("######ESTUDIANDO######")
print("######APRENDIENDO######")
print("#SE CREARAN PROYECTOS#")
print("🚀🐍😃💻🧠🧑‍💻🎓📚🧮🎮💡🎵👌🧮")
print("#        💡            #")
print(" ##LA FRASE DEL DÍA ES##")
print("EL CONOCIMIENTO ES PODER😎")
print("ENTONCES APLIQUEMOSLO💪🏻")
print("BIENVENIDO CICLO 2025-2026🕣")